name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:prod
        env:
          FIREBASE_TOKEN: ${{ secrets.1//0gKQG6_vkcn8RCgYIARAAGBASNwF-L9IrMeuwP7-y3MIi9Rrp4Fdj2Mtt7O19SpIhO2eoZU5keSnxoCdPuYXP2YoLf8iw9SA0pL0 }}
