name: Build and 
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: w9jds/firebase-action@master
        uses: akshayknz/Mystrix@master
        with:
          args: deploy --only hosting:prod
        env:
          FIREBASE_TOKEN: //0gKQG6_vkcn8RCgYIARAAGBASNwF-L9IrMeuwP7-y3MIi9Rrp4Fdj2Mtt7O19SpIhO2eoZU5keSnxoCdPuYXP2YoLf8iw9SA0pL0
